config/routes.rb
FacebookAuth::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  namespace :admin do
    resources :users
  end
  resources :admin  

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable, :oauthable

  devise :database_authenticatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :admin, :active


  def display_name
    full_name = "#{first_name} #{last_name}".strip
    full_name = self.email if full_name.blank?    
    full_name
  end
  
  def facebook_avatar_url
    "http://graph.facebook.com/#{self.facebook_id}/picture" if self.facebook_id.present?
  end

  
private
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user.update_attribute(:facebook_id, data[:id]) if data[:id].present?
      user.update_attributes(:first_name => data[:first_name], :last_name => data[:last_name])
      user
    else # Create a user with a stub password. 
      User.create!(:email => data.email, :password => Devise.friendly_token[0,20]) 
    end
  end 
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  def index
    @users = User.paginate(default_pagination_params)  
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:active, false)
    flash[:notice] = "You have successfully inactivated #{@user.display_name}'s account"
    redirect_to admin_users_path
  end
  
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank? 
      params[:user].delete(:password) 
      params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank? 
    end 
    if @user.update_attributes(params[:user])
      flash[:notice] = "You successfully updated #{@user.display_name}'s account"
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "You successfully create a new user"
      redirect_to admin_users_path
    else
      render 'new'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :authenticate_user
  
  def show
  end


  private

    def authenticate_user
       if (@user = User.find(params[:id])) != current_user
         redirect_to user_path(current_user)
       end
    end
end

app/views/admin/users/_form.html.haml
= f.error_messages


%table{:border => 0, :width => '100%'}
  %tr
    %td{:width => '50%', :valign => 'top'}
      -if current_user.try(:admin?)
        %br
        Admin?
        %br
        =f.check_box :admin

        %br
        Active?
        %br
        =f.check_box :active    
        %br
        %br
        %br

    
 
= f.submit text, :class => 'btn btn-primary'

app/views/admin/users/edit.html.haml
.page-header
  %h1
    =image_tag(@user.facebook_avatar_url) if @user.facebook_avatar_url.present?  
    Edit user account
    %small
      =@user.display_name
    .btn-group.pull-right
      = link_to admin_index_path, :class => 'btn' do
        %i.icon-arrow-left
        Back to Admin 
      = link_to admin_users_path, :class => 'btn' do
        %i.icon-arrow-left
        Back to Users             

= form_for [:admin, @user], :builder => AppFormBuilder do |f| 
  = render :partial => 'form', :locals => {:f => f, :text => 'Update User!'}
  =link_to "Cancel", admin_users_path, :class => 'btn btn-danger'

app/views/admin/users/index.html.haml
.page-header
  %h1
    Accounts
    %small
      All users who have logged in with Facebook
      .btn-group.pull-right
        = link_to admin_index_path, :class => 'btn' do
          %i.icon-arrow-left
          Back to Admin
     
%br
- if @users
  = page_entries_info @users, :model => 'User' 
%br
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th
      %th
        Display Name
      %th
        Active?
      %th
        Admin?
      %th
        Email
      %th
        Created at
      %th
        Actions
  %tbody
    -@users.each do |u|
      %tr
        %td{:style => 'text-align:center'}
          =image_tag(u.facebook_avatar_url) if u.facebook_avatar_url 
        %td
          =u.display_name              
        %td
          =status_image u.active?
        %td
          =status_image u.admin?, ['Yes', 'No']         
        %td
          =u.email
        %td
          =u.created_at.to_formatted_s(:short_with_year)
        %td
          %span{:style => 'white-space: nowrap'}
            =action_links [:admin, u], :exclude => [:index, :show], :delete => {:title => 'Inactivate', :alt_text => 'Inactivate', :confirm => 'Are you sure you want to inactivate this user'}
    -if @users.total_pages > 1
      %tr
        %td{:colspan => 7}
          = will_paginate @users, :renderer => 'WillPaginateHelper::LinkRenderer'          